image: "ruby:2.3"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

variables:
  CI_SCRIPTS_VERSION: git

before_script:
  - ruby -v                                   # Print out ruby version for debugging
  - wget -qO- https://raw.githubusercontent.com/benjamincaldwell/ci-scripts/master/install | bash

rubocop:
  script:
  - ci-scripts ruby/rubocop

