image: "ruby:2.3"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v                                   # Print out ruby version for debugging
  - gem install ci-scripts

rubocop:
  script:
  - ci-scripts ruby/bundler
  - ci-scripts ruby/rubocop
  - ci-scripts ruby/rake_test

