#!/usr/bin/bash
set -e

# set TMPDIR to /tmp if it doesnt exist
if [ -z "$TMPDIR" ]; then
  export TMPDIR=/tmp
fi

install_location=${CI_SCRIPTS_INSTALL_LOCATION:="/opt/ci-scripts"}

install_version=${CI_SCRIPTS_VERSION:="latest"}

echo "Installing ci-scripts-${install_version} to ${install_location}"

_ci_scripts_install_version() {
  local tar_file="${TMPDIR}/ci-scripts.tar.gz"
  local extracted_folder="${TMPDIR}/ci-scripts-$1"
  wget "https://github.com/benjamincaldwell/ci-scripts/archive/v$1.tar.gz" -O "${tar_file}"
  tar -zxvf "${tar_file}" -C "${TMPDIR}"
  _ci_scripts_sudo mv "${extracted_folder}" "${install_location}"
  rm -rf "${extracted_folder}" "${tar_file}"
}

_ci_scripts_sudo() {
  SUDO=''
  if [ "$(whoami)" != "root" ]; then
      SUDO='sudo'
  fi
  $SUDO $1
}

case "$install_version" in
  git)
    _ci_scripts_sudo git clone git://github.com/benjamincaldwell/ci-scripts.git "${install_location}"
    ;;
  latest)
    echo "guh"
    ;;
  *)
    _ci_scripts_install_version "$install_version"
    ;;
esac

_ci_scripts_sudo ln -snf /opt/ci-scripts/bin/ci-scripts /usr/bin/ci-scripts
