go:
  build:
    go_build_args: -output .ci-build/{{.OS}}_{{.Arch}} -osarch=linux/amd64 -osarch=linux/arm64 -osarch=darwin/amd64 ./cmd/ciscripts

github:
  release:
    path: .ci-build
    delete: true
