# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  release:
    docker:
      # specify the version
      - image: cimg/go:1.20.0
    environment:
      CI_SCRIPTS_CONFIG: ./.circleci/ci_scripts.yml
      GITHUB_RELEASE_TAG: latest
      CGO_ENABLED: 0

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go install ./cmd/ciscripts/ci-scripts.go
      - run: ci-scripts go/build
      - run: ci-scripts github/release

  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/ci-scripts

workflows:
  version: 2
  release:
    jobs:
      - release:
          context: bot-github
      - release-docker:
          context: docker
