# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  release:
    docker:
      # specify the version
      - image: circleci/golang:1.13
    environment:
      CI_SCRIPTS_CONFIG: ./.circleci/ci_scripts.yml
      GITHUB_RELEASE_TAG: latest
      GO111MODULE: "on"
      CGO_ENABLED: 0

    working_directory: /go/src/github.com/bcaldwell/ci-scripts

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go install ci-scripts.go
      - run: ci-scripts go/build
      - run: ci-scripts github/release

  release-docker:
    docker:
      - image: docker:19

    working_directory: /go/src/github.com/bcaldwell/ci-scripts

    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache git
        # docker_layer_caching: true
      # specify any bash command here prefixed with `run: `
      - run:
          name: Install ci-scripts
          command: wget -q -O - https://raw.githubusercontent.com/bcaldwell/ci-scripts/master/scripts/install.sh | sh

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/ci-scripts

workflows:
  version: 2
  release:
    jobs:
      - release
      - release-docker
