#!/usr/bin/ruby
puts ARGV[0]
if ARGV[0]
  require ARGV[0]
else
  require_relative "../lib/base.rb"
end

# set image tag if it hasnt been set
required_env("DOCKER_USERNAME")
required_env("DOCKER_PASSWORD")
required_env("DOCKER_IMAGE")

env_check("IMAGE_TAG", `git rev-parse HEAD`)
env_check("DOCKER_REGISTRY", "https://hub.docker.com")

# login to docker hub
command('docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY')

# build docker image
command('docker build --pull -t "$DOCKER_IMAGE:$IMAGE_TAG" .')

# push docker image
command('docker push "$DOCKER_IMAGE:$IMAGE_TAG"')
