#!/usr/bin/ruby

module Docker
  extend self
  def herokuish  
    # set image tag if it hasnt been set
    # also has to support old ruby versions
    dockerfile_contents = <<-DOCKERFILE
FROM gliderlabs/herokuish

COPY . /app

RUN /bin/herokuish buildpack build

CMD ["/start", "web"]
    DOCKERFILE

    timed_run "Creating herokuish dockerfile" do 
      File.write("Dockerfile.herokuish", dockerfile_contents)

      ENV["BUILD_DOCKERFILE"] = "Dockerfile.herokuish"
    end

    run_script("docker/build")

    Docker.build
  end
end

# if main file require base and run main function
if __FILE__ == $PROGRAM_NAME
  base_path = 
  if ARGV[0]
    ARGV[0]
  else
    File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib/base.rb'))
  end

  unless File.file?(base_path)
    puts "Can't find base ruby file at #{base_path}"
    exit 1
  end
  require base_path

  Docker.herokuish
end
