#!/usr/bin/bash

# determine default image tag
if [ -z "$IMAGE_TAG" ]; then
  export IMAGE_TAG=$(git rev-parse HEAD)
fi

# set latest branch to master
if [ -z "$LATEST_BRANCH" ]; then
  export LATEST_BRANCH=master
fi

# build image if it doesnt exist

# tag and push latest if on default branch
