#!/usr/bin/ruby
base_path = 
  if ARGV[0]
    ARGV[0]
  else
    File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib/base.rb'))
  end

unless File.file?(base_path)
  puts "Can't find base ruby file at #{base_path}"
  exit 1
end
require base_path

module Docker
  extend self
  def push_branch
    required_env("DOCKER_IMAGE")

    # set image tag if it hasnt been set
    env_check("IMAGE_TAG", `git rev-parse HEAD`.strip)

    branch = `git rev-parse --abbrev-ref HEAD`.strip

    # tag image
    command("docker tag \"$DOCKER_IMAGE:$IMAGE_TAG\" \"$DOCKER_IMAGE:#{branch}\"")

    # push docker image
    command("docker push \"$DOCKER_IMAGE:#{branch}\"")
  end
end

Docker.push_branch if __FILE__ == $PROGRAM_NAME
